// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ60TUFkoRRQPoAZYdHM0K4piy_vkHRfQ',
    appId: '1:768408825614:web:10f391eef602eab7b6715f',
    messagingSenderId: '768408825614',
    projectId: 'class-activity-13-b636a',
    authDomain: 'class-activity-13-b636a.firebaseapp.com',
    storageBucket: 'class-activity-13-b636a.firebasestorage.app',
    measurementId: 'G-G2DC7349G2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZAisDgNu2sbCrNuSLkUUHbO8IStDrTXs',
    appId: '1:768408825614:android:5c2ff193c00cbf04b6715f',
    messagingSenderId: '768408825614',
    projectId: 'class-activity-13-b636a',
    storageBucket: 'class-activity-13-b636a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUCCpXJjwBR5xeBDDXbnEcyefd5UQT680',
    appId: '1:768408825614:ios:82b18b491ca42cbfb6715f',
    messagingSenderId: '768408825614',
    projectId: 'class-activity-13-b636a',
    storageBucket: 'class-activity-13-b636a.firebasestorage.app',
    iosBundleId: 'com.example.classActivity13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUCCpXJjwBR5xeBDDXbnEcyefd5UQT680',
    appId: '1:768408825614:ios:82b18b491ca42cbfb6715f',
    messagingSenderId: '768408825614',
    projectId: 'class-activity-13-b636a',
    storageBucket: 'class-activity-13-b636a.firebasestorage.app',
    iosBundleId: 'com.example.classActivity13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ60TUFkoRRQPoAZYdHM0K4piy_vkHRfQ',
    appId: '1:768408825614:web:d15d16029c41fd03b6715f',
    messagingSenderId: '768408825614',
    projectId: 'class-activity-13-b636a',
    authDomain: 'class-activity-13-b636a.firebaseapp.com',
    storageBucket: 'class-activity-13-b636a.firebasestorage.app',
    measurementId: 'G-0VWJ559RRY',
  );

}